name: build

on:
  push:
    tags: ["v*.*.*"]

  workflow_dispatch:

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload to COS
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_SECRET_KEY }}
          cos_bucket: elion-demo-1308722423
          cos_region: ap-shanghai
          local_path: build
          clean: true

      - name: Refresh CDN
        uses: TencentCloud/cli-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_SECRET_KEY }}
          region: ap-shanghai
          commands: "cdn PurgePathCache --cli-unfold-argument --Paths https://elion-demo.xhpolaris.com/ --FlushType delete"
          output_format: json
      - name: Send Notification
        if: startsWith(github.ref, 'refs/tags')
        uses: xh-polaris/send-changelog@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          title: 作文辅导系统更新日志
